<?php

namespace App\Form;

use App\Entity\Recherche;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenom',TextType::class,[
                'required'=> false,
                'label'=>false,
                'attr'=>['placeholder'=>'prenom']
            ])
            ->add('matricule',TextType::class,[
                'required'=> false,
                'label'=>false,
                'attr'=>['placeholder'=>'matricule']
            ])
            ->add('telephone',NumberType::class,[
                'required'=> false,
                'label'=>false,
                'attr'=>[
                    'placeholder'=>'telephone'
                ]
            ])
            ->add('nom',TextType::class,[
                'required'=> false,
                'label'=>false,
                'attr'=>['placeholder'=>'nom']
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recherche::class,
            'method'=> 'get',
            'csrf_protection'=> false
        ]);
    }
    public function getBlockPrefix()
    {
        return ""; // TODO: Change the autogenerated stub
    }
}
